<a href="https://colab.research.google.com/github/xuyuelin88117/credit-for-Heuristic-Algorithms/blob/main/%D0%B7%D0%B0%D1%87%D1%91%D1%82_%D0%BF%D0%BE_%22%D0%AD%D0%B2%D1%80%D0%B8%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%BC_%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D0%B0%D0%BC%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Импортные пакеты

In [60]:
import numpy as np
import random

generate_matrix - это функция, которая генерирует булеву квадратную матрицу размерности N, используя один из двух предложенных методов (В) или (Г). Входные параметры функции:

N: размер матрицы (N x N)
p: вероятность, требуемая для метода (В), варьируется от 0 до 1
mean: математическое ожидание количества генерируемых сеток, требуемое для метода (Г)
std: стандартное отклонение количества сеток, требуемое для метода (Г)
min_size: минимальный размер сетки (по горизонтали и вертикали), требуемый для метода (Г)
max_size: максимальный размер сетки (по горизонтали и вертикали), требуемый для метода (Г)
Функция сначала проверяет, указана ли вероятность p. Если да, то матрица генерируется с использованием метода (В). В этом случае мы используем функцию random.choice из библиотеки numpy для случайного назначения 0 или 1 для каждого элемента матрицы с вероятностью p.

Если указаны параметры среднего значения, стандартного отклонения, минимального размера и максимального размера, функция генерирует матрицу с использованием метода (Г). Сначала создается матрица N x N, заполненная нулями. Затем из нормального распределения генерируется количество сеток на основе заданных среднего значения и стандартного отклонения, причем количество сеток должно быть не меньше 1. Далее для каждой сетки генерируется случайный подмассив с случайными размерами и вставляется в основную матрицу на случайную позицию. При вставке следим за тем, чтобы все сетки были равновероятными.

Если не указаны достаточные параметры для выполнения одного из методов, функция вызывает ошибку значения.

generate_matrix функция создает квадратную булеву матрицу размерности N с использованием двух методов заполнения:

Простой метод (В): Задается вероятность от 0 до 1, и каждая ячейка равна 1 с этой вероятностью.
Сложный метод (Г): Генерация гридов с учетом математического ожидания, дисперсии и других параметров. Затем случайно генерируется каждый грид и добавляется в матрицу.

generate_matrix是一个函数，它使用所提出的两种方法之一（C）或（D）生成一个维数为N的布尔方形矩阵。该函数的输入参数是：

N：矩阵的大小(N x N)
p：方法（C）要求的概率，范围是0到1
平均值：方法（D）所要求的生成网格数量的数学期望值
std：方法（D）所需网目数的标准偏差
min_size：方法要求的最小网格尺寸（水平和垂直）(D)
max_size：该方法所需的最大网目尺寸（水平和垂直）(D)
该函数首先检查是否指定了概率p。如果是，则使用方法（C）生成矩阵。在这种情况下，我们使用numpy库中的random.choice函数为每个矩阵元素随机分配0或1的概率p。

如果指定了平均值、标准差、最小尺寸和最大尺寸的参数，该函数将使用方法（D）生成矩阵。首先，生成一个充满零的N×N矩阵。然后根据给定的均值和标准差从正态分布中生成若干网格，网格的数量必须至少为1。然后为每个网格生成一个具有随机尺寸的随机子阵列，并在一个随机位置插入主矩阵中。插入时，要确保所有网格的概率相等。

如果为这两种方法指定的参数不足，该函数会导致一个值错误。

generate_matrix函数使用两种填充方法创建一个维数为N的正方形布尔矩阵：

简单方法（C）：指定0到1的概率，每个单元格的概率等于1。
复杂方法（D）：用期望值、方差和其他参数生成网格。然后每个网格都是随机生成的，并添加到矩阵中。

In [61]:
def generate_matrix(N, p=None, mean=None, std=None, min_size=None, max_size=None):
    if p is not None:
        return np.random.choice([0, 1], size=(N, N), p=[1 - p, p])
    elif mean is not None and std is not None and min_size is not None and max_size is not None:
        matrix = np.zeros((N, N), dtype=int)
        num_grids = max(1, int(np.random.normal(loc=mean, scale=std)))
        
        for _ in range(num_grids):
            grid_rows = random.randint(min_size, max_size)
            grid_cols = random.randint(min_size, max_size)
            grid = np.random.choice([0, 1], size=(grid_rows, grid_cols), p=[0.5, 0.5])
            
            row_offset = random.randint(0, N - grid_rows)
            col_offset = random.randint(0, N - grid_cols)
            
            for i in range(grid_rows):
                for j in range(grid_cols):
                    matrix[row_offset + i, col_offset + j] |= grid[i, j]
        return matrix
    else:
        raise ValueError("Invalid arguments")

Функция count_grids() вычисляет количество связных единиц в данной матрице. Она реализована с использованием алгоритма поиска в глубину (DFS).

Сначала функция определяет внутреннюю функцию dfs(), которая использует DFS для поиска всех единиц в связной компоненте и помечает их как 0, чтобы избежать повторных вычислений.

Затем функция проходит по всей матрице и для каждого значения 1 вызывает функцию dfs() для вычисления количества единиц в связной компоненте, в которой оно находится. При каждом вызове функции dfs() все найденные единицы помечаются как 0, чтобы избежать повторных вычислений.

В конце функция возвращает количество связных единиц.

Временная сложность этой функции равна $O(mn)$, где $m$ и $n$ - это количество строк и столбцов матрицы. Поскольку функция проходит по всей матрице один раз, а для каждой позиции со значением 1 она обходит не более одного связного компонента, то сложность не превышает $O(mn)$.

count_grids() 函数计算给定矩阵中连通的1的数量。它的实现使用了深度优先搜索 (DFS) 算法。

该函数首先定义了一个内部函数 dfs()，它使用 DFS 来查找一个连通分量中的所有1，并将这些1标记为0，以避免重复计算。

然后，函数遍历整个矩阵，并对于每个值为1的位置，调用 dfs() 函数来计算它所在的连通分量中的1的数量。每次调用 dfs() 函数都会将找到的所有1标记为0，以避免重复计算。

最后，函数返回连通的1的数量。

这个函数的时间复杂度为 $O(mn)$，其中 $m$ 和 $n$ 分别是矩阵的行数和列数。因为函数遍历整个矩阵一次，对于每个1的位置，最多只会遍历整个连通分量一次。

In [62]:
def count_grids(matrix):
    def dfs(matrix, i, j):
        if 0 <= i < len(matrix) and 0 <= j < len(matrix[0]) and matrix[i][j] == 1:
            matrix[i][j] = 0
            dfs(matrix, i - 1, j)
            dfs(matrix, i + 1, j)
            dfs(matrix, i, j - 1)
            dfs(matrix, i, j + 1)

    count = 0

    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if matrix[i][j] == 1:
                count += 1
                dfs(matrix, i, j)

    return count

In [65]:
N = 15
# Сгенерируйте матрицу, используя метод (В) 用方法 (В) 生成矩阵
matrix_V = generate_matrix(N, p=0.5)
print("Метод (В) Генерируемая матрица.")
print(matrix_V)

# Сгенерируйте матрицу, используя метод (Г) 用方法 (Г) 生成矩阵
matrix_G = generate_matrix(N, mean=25, std=2, min_size=1, max_size=N)
print("Матрица, сгенерированная методом (Г).")
print(matrix_G)

# посчитать число гридов(В конце функция возвращает количество связных единиц.) в заданной матрице 计算矩阵中的网格数
grids_count_V = count_grids(matrix_V)
print("Метод (В) Количество гридов в генерируемой матрице:", grids_count_V)

grids_count_G = count_grids(matrix_G)
print("Метод (Г) Количество гридов в генерируемой матрице:", grids_count_G)


Метод (В) Генерируемая матрица.
[[1 1 0 0 1 1 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 1 0 1 0 1 1 0 0 0]
 [1 0 0 1 0 0 1 1 1 1 0 1 0 0 0]
 [1 0 1 0 1 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1 0 1 0 1 1 1 0]
 [0 0 1 0 1 0 1 1 0 1 0 1 1 1 1]
 [1 1 1 0 1 1 1 0 1 0 1 0 1 0 0]
 [1 0 0 0 0 0 1 1 1 0 1 0 1 1 1]
 [0 1 1 0 0 1 0 1 1 0 1 1 0 0 1]
 [0 0 1 0 1 0 1 1 1 1 0 0 0 1 1]
 [1 1 0 0 0 1 0 0 1 1 0 1 0 0 1]
 [1 1 1 1 1 0 1 1 0 0 1 0 0 0 0]
 [1 0 1 1 0 0 1 0 1 1 0 1 0 1 1]
 [1 1 0 1 0 1 1 0 0 1 1 0 0 0 0]
 [0 1 0 1 0 1 0 0 0 0 1 0 1 1 0]]
Матрица, сгенерированная методом (Г).
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 0